import type { ReactNode } from 'react';
import { Layout } from '../components/Layout';

const CONTACT = 'soporte@truly.dating';
const UPDATED = 'July 2026';

function LegalPage({ title, children }: { title: string; children: ReactNode }) {
  return (
    <Layout>
      <div className="mk-narrow mk-page mk-legal" style={{ maxWidth: '46rem' }}>
        <h1>{title}</h1>
        <p className="updated">Last updated: {UPDATED}</p>
        <div className="prose">{children}</div>
      </div>
    </Layout>
  );
}

export function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>
        Truly is a service operated by rgytgroup ("we", "us") that provides an AI-generated audit
        of your dating profile, and, on the premium tier, AI-generated photos based on the pictures
        you upload. By purchasing or using Truly you agree to these Terms.
      </p>

      <h2>What you get</h2>
      <p>
        Truly is a <strong>one-time purchase</strong>. There are no subscriptions or recurring
        charges. You receive a report with scores, a diagnosis, rewritten bios, suggested prompts,
        and an action plan. The premium tier additionally generates AI photos of you.
      </p>

      <h2>Your responsibilities</h2>
      <p>You agree that you will only upload photos that:</p>
      <ul className="list-disc space-y-1 pl-5">
        <li>depict you, or a person who has consented to your use of their images;</li>
        <li>are not of a minor (anyone under 18); and</li>
        <li>you have the legal right to use.</li>
      </ul>
      <p>
        We run an automated moderation check and may reject or refund submissions that appear to
        violate these rules.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Reports and photos are generated by AI and are provided for guidance and entertainment. We
        do not guarantee specific results (such as more matches). AI photos change context, clothing
        and lighting — they do not alter your physical features or identity.
      </p>

      <h2>Disclaimer &amp; liability</h2>
      <p>
        The service is provided "as is", without warranties of any kind. To the maximum extent
        permitted by law, our total liability for any claim is limited to the amount you paid for the
        service.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms? Email us at{' '}
        <a className="underline" href={`mailto:${CONTACT}`}>
          {CONTACT}
        </a>
        .
      </p>
    </LegalPage>
  );
}

export function Privacy() {
  return (
    <LegalPage title="Privacy Policy">
      <p>
        This policy explains what data Truly (operated by rgytgroup) collects and how we use it.
      </p>

      <h2>What we collect</h2>
      <ul className="list-disc space-y-1 pl-5">
        <li>Your email address (to deliver your report and receipts).</li>
        <li>The photos, bio and questionnaire answers you submit for the audit.</li>
        <li>Payment information — handled directly by Stripe; we never see your card details.</li>
        <li>Basic analytics events (e.g. page visits, checkout, purchase) to improve the product.</li>
      </ul>

      <h2>How we use it</h2>
      <p>
        We use your submission solely to generate your report and, on the premium tier, your AI
        photos, and to email you the results. We do not sell your data.
      </p>

      <h2>Service providers</h2>
      <p>
        We share data with the processors needed to run the service: Supabase (database and file
        storage), Stripe (payments), Google Gemini (analysis), Replicate (AI photos) and Resend
        (email). Each processes data only to provide their function.
      </p>

      <h2>Data retention</h2>
      <p>
        Your uploaded and generated photos are <strong>automatically deleted after 30 days</strong>.
        Your report is retained so you can keep accessing it via its private link.
      </p>

      <h2>Your rights</h2>
      <p>
        You can request deletion of your data or a copy of it at any time by emailing{' '}
        <a className="underline" href={`mailto:${CONTACT}`}>
          {CONTACT}
        </a>
        .
      </p>
    </LegalPage>
  );
}

export function Refunds() {
  return (
    <LegalPage title="Refund Policy">
      <p>
        We want you to be happy with your Truly audit. If you are not satisfied, you can request a
        full refund within <strong>7 days</strong> of your purchase.
      </p>

      <h2>How to request a refund</h2>
      <p>
        Just email us at{' '}
        <a className="underline" href={`mailto:${CONTACT}`}>
          {CONTACT}
        </a>{' '}
        with the email address you used to purchase. We will process the refund and stop any
        processing that is still in progress.
      </p>

      <h2>After a refund</h2>
      <p>
        Once refunded, your order is closed and any active analysis or photo generation is stopped.
        Refunds appear on your statement within a few business days.
      </p>
    </LegalPage>
  );
}
